%1 clean -i github.com/TWINGSISTER/docker-machine-driver-qemu/...
%1 install -v -gcflags "-N -l" github.com/TWINGSISTER/docker-machine-driver-qemu/...
%1 build  -v -gcflags "-N -l" -o Z:\docker-toolbox-portable-win32-18.09.1-7\app\docker-machine-driver-qemu.exe github.com/TWINGSISTER/docker-machine-driver-qemu/src/driver/cmd/main.go